### ISSUE TITLE
[REFACTOR] 플레이어 데이터 렌더링 최적화

### ISSUE THREAD

**Issue by spearStr** [boostcampwm-2024/web22-LiBoo#213]
### ⚽️ 어떤 기능인가요?
> 클라이언트 페이지에서 매 시간마다 페이지가 전체 렌더링 되는 현상 해결

### 🏀 작업 상세 내용
- [ ] TODO
- [ ] TODO
- [ ] TODO

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented React.memo for components, moved streaming state to ClientView, and used useCallback for functions passed as props to optimize rendering and solve the issue of the entire page re-rendering every hour.

You can review changes in this commit: https://github.com/lkilu6456546/boostcampwm-2024-web22-LiBoo-213/commit/cacba02545d174ceafe2a15167f6b02851d52cbe.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
